<a href="https://colab.research.google.com/github/rajkhatana/Khatana/blob/master/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:

a = np.ones((3,3)) # a.shape = (12288, 150)
b = 2*np.ones((3,1)) # b.shape = (150, 45)
c = a*b
c

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [0]:
for i in range(3):
  for j in range(3):
    c[i][j] = a[i][j] + b[j]

In [0]:
c

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [0]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
c

array([[ 0.86818981,  0.59812703, -1.56531924],
       [ 0.8223537 , -0.32937331, -0.03040739],
       [-0.38781158,  1.0574382 , -0.10192749]])

In [0]:
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)
B.shape


(4, 1)

In [0]:
cost = (-1/m)*sum(Y*np.log(AL)-(1-Y)*np.log(1-AL))

In [0]:
    dW = (dZ.dot(A_prev)/m
    db = (sum(dZ))/m
    dA_prev = W.T.dot(dZ)